# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm i
          cd packages/@huyikai/vitepress-helper
          npm run build
      - name: Publish
        run: |
          npm publish --access public
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
